name: Deploy to DigitalOcean App Platform

on:
  workflow_call:
    inputs:
      app_name:
        description: "Name of the app on DigitalOcean App Platform"
        required: true
        type: string
      component_name:
        description: "Component name of the app (e.g., backend service)"
        required: true
        type: string
      repository:
        description: "Docker repository for the app"
        required: true
        type: string
      tag:
        description: "Docker image tag"
        required: true
        type: string
    secrets:
      access_token:
        description: "DigitalOcean API access token"
        required: true
      registry:
        description: "Docker Hub username"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install DigitalOcean CLI (doctl)
      - name: Install doctl (DigitalOcean CLI)
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.90.0/doctl-1.90.0-linux-amd64.tar.gz | tar xz
          sudo mv doctl /usr/local/bin

      # Step 2: Authenticate with DigitalOcean
      - name: Authenticate with DigitalOcean
        run: doctl auth init -t ${{ secrets.access_token }}

      # Step 3: Set environment variables for the DigitalOcean app platform
      - name: Set environment variables for deployment
        run: |
          echo "APP_NAME=${{ inputs.app_name }}" >> $GITHUB_ENV
          echo "COMPONENT_NAME=${{ inputs.component_name }}" >> $GITHUB_ENV
          echo "REPOSITORY=${{ inputs.repository }}" >> $GITHUB_ENV
          echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV
          echo "REGISTRY=${{ secrets.registry }}" >> $GITHUB_ENV

      # Step 4: Deploy to DigitalOcean App Platform
      - name: Deploy to DigitalOcean App Platform
        run: |
          # Update app with the new Docker image
          doctl apps update $APP_NAME --component $COMPONENT_NAME --image $REGISTRY/$REPOSITORY:$TAG

      # Step 5: Verify the deployment
      - name: Check App Status
        run: |
          doctl apps get $APP_NAME --json
          echo "Deployment complete for app $APP_NAME."
