name: Dockerhub Publish Workflow

on:
  # The workflow is triggered manually with inputs and secrets passed
  workflow_call:
    secrets:
      # Docker username secret (used for logging into Docker Hub)
      docker_username:
        description: Docker username
        required: true
      # Docker password secret (used for logging into Docker Hub)
      docker_password:
        required: true
        description: Docker password

    inputs:
      # Tag input (specifies the version/tag of the Docker image)
      tag:
        description: Image tag name
        type: string
        required: true

      # Image name input (specifies the name of the Docker image)
      image_name:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest # Runs on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Check out the repository code to the workflow

      - name: Docker Login
        uses: docker/login-action@v3.1.0 # Log in to Docker Hub
        with:
          # Use the secrets for secure login to Docker Hub
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Docker Build and Push image
        uses: docker/build-push-action@v5.3.0 # Build and push the Docker image
        with:
          context: . # The build context is the root directory of the repository
          push: true # Enable image pushing to Docker Hub
          tags: ${{ secrets.docker_username }}/${{ inputs.image_name }}:latest
